In [98]:
print("=== 5 KEY INSIGHTS ===")
print("1. Worst state by cases:", df.loc[df['Total Cases'].idxmax(), 'State/UTs'])
print("2. Highest CFR state  :", df.loc[df['CFR'].idxmax(), 'State/UTs'], "-", df['CFR'].max(), "%")
print("3. Best recovery state:", df.loc[df['Recovery Rate'].idxmax(), 'State/UTs'])
print("4. National recovery rate:", np.round((df['Discharged'].sum()/df['Total Cases'].sum())*100, 2), "%")
print("5. Correlation cases vs deaths:", np.round(np.corrcoef(df['Total Cases'].values, df['Deaths'].values)[0,1], 4))

=== 5 KEY INSIGHTS ===
1. Worst state by cases: Maharashtra
2. Highest CFR state  : Punjab - 2.44 %
3. Best recovery state: Dadra and Nagar Haveli and Daman and Diu
4. National recovery rate: 98.81 %
5. Correlation cases vs deaths: 0.9446

In [97]:
print("=== FINAL ANALYZED DATASET ===")
final = df[['State/UTs','Total Cases','Deaths','CFR','Recovery Rate','Cases per Million']].sort_values('Total Cases', ascending=False)
print(final.to_string(index=False))
df.to_csv("covid_india_analyzed.csv",index=False)
print("\nSaved Successfully!")

=== FINAL ANALYZED DATASET ===
                               State/UTs  Total Cases  Deaths  CFR  Recovery Rate  Cases per Million
                             Maharashtra      8171048  148558 1.82          98.18         20478766.0
                                  Kerala      6907241   72042 1.04          98.96            75322.0
                               Karnataka      4088769   40358 0.99          99.01          2388374.0
                              Tamil Nadu      3610655   38081 1.05          98.95           100299.0
                          Andhra Pradesh      2340676   14733 0.63          99.37            18215.0
                           Uttar Pradesh      2145431   23712 1.11          98.89          1852640.0
                             West Bengal      2126282   21555 1.01          98.98            66034.0
                                   Delhi      2040910   26666 1.31          98.69          2636845.0
                                  Odisha      1348409    9215 0.68          99.31            69862.0
                               Rajasthan      1326465    9736 0.73          99.27           871532.0
                                 Gujarat      1291383   11079 0.86          99.14            18343.0
                            Chhattisgarh      1187695   14190 1.19          98.81            41096.0
                                 Haryana      1078903   10755 1.00          99.00           143796.0
                          Madhya Pradesh      1056351   10786 1.02          98.98            70426.0
                                   Bihar       855267   12314 1.44          98.56            21328.0
                               Telengana       844432    4111 0.49          99.51            12133.0
                                  Punjab       793644   19338 2.44          97.41            22872.0
                                   Assam       746159    8035 1.08          98.92          2568604.0
                       Jammu and Kashmir       482023    4792 0.99          99.01          7303268.0
                             Uttarakhand       452571    7768 1.72          98.28             5324.0
                               Jharkhand       443826    5334 1.20          98.80             3553.0
                        Himachal Pradesh       322905    4241 1.31          98.69            93951.0
                                     Goa       263346    4014 1.52          98.47            69814.0
                                 Mizoram       239560     734 0.31          99.69           183015.0
                              Puducherry       177547    1981 1.12          98.88            85644.0
                                 Manipur       140034    2149 1.53          98.47             2973.0
                                 Tripura       108493     942 0.87          99.13            65911.0
                              Chandigarh       100693    1185 1.18          98.82             3301.0
                               Meghalaya        96983    1628 1.68          98.32             1220.0
                       Arunachal Pradesh        67049     296 0.44          99.56           101895.0
                                  Sikkim        44927     501 1.12          98.88              537.0
                                Nagaland        36033     782 2.17          97.83              944.0
                                  Ladakh        29602     231 0.78          99.22             7073.0
Dadra and Nagar Haveli and Daman and Diu        11592       4 0.03          99.97               50.0
                             Lakshadweep        11415      52 0.46          99.54              976.0
                     Andaman and Nicobar        10766     129 1.20          98.80              107.0

Saved Successfully!

In [95]:
print("=== CASES PER MILLION POPULATION ===")
df['Cases per Million'] = np.round((df['Total Cases'].values/df['Population'].values)*1_000_000, 0)
df['Deaths per Million'] = np.round((df['Deaths'].values/df['Population'].values)*1_000_000, 0)
result = df[['State/UTs','Cases per Million','Deaths per Million']].sort_values('Cases per Million', ascending=False).head(10).reset_index(drop=True)
result.index += 1
print(result)

=== CASES PER MILLION POPULATION ===
            State/UTs  Cases per Million  Deaths per Million
1         Maharashtra         20478766.0            372325.0
2   Jammu and Kashmir          7303268.0             72605.0
3               Delhi          2636845.0             34452.0
4               Assam          2568604.0             27660.0
5           Karnataka          2388374.0             23574.0
6       Uttar Pradesh          1852640.0             20476.0
7           Rajasthan           871532.0              6397.0
8             Mizoram           183015.0               561.0
9             Haryana           143796.0              1433.0
10  Arunachal Pradesh           101895.0               450.0

In [88]:
print("=== NUMPY STATS + OUTLIER DETECTION ===")
cases = df['Total Cases'].values
print(f"Mean   : {np.mean(cases):,.0f}")
print(f"Median : {np.median(cases):,.0f}")
print(f"Std    : {np.std(cases):,.0f}")
Q1  = np.percentile(cases, 25)
Q3  = np.percentile(cases, 75)
IQR = Q3 - Q1
upper = Q3 + 1.5*IQR
print(f"\nOutlier threshold: above {upper:,.0f}")
outliers = df[df['Total Cases'] > upper][['State/UTs','Total Cases']]
print("Outlier states:")
print(outliers.to_string(index=False))
corr = np.corrcoef(df['Total Cases'].values, df['Deaths'].values)[0,1]
print(f"\nCorrelation (Cases vs Deaths): {corr:.4f}")

=== NUMPY STATS + OUTLIER DETECTION ===
Mean   : 1,249,975
Median : 614,091
Std    : 1,820,218

Outlier threshold: above 3,170,063
Outlier states:
  State/UTs  Total Cases
  Karnataka      4088769
     Kerala      6907241
Maharashtra      8171048
 Tamil Nadu      3610655

Correlation (Cases vs Deaths): 0.9446

In [71]:
print("=== RECOVERY RATE RANKING ===")
df['Recovery Rate'] = np.round((df['Discharged'].values/df['Total Cases'].values)*100, 2)
ranked = df[['State/UTs','Recovery Rate']].sort_values('Recovery Rate', ascending=False).reset_index(drop=True)
ranked.index += 1
print(ranked)

=== RECOVERY RATE RANKING ===
                                   State/UTs  Recovery Rate
1   Dadra and Nagar Haveli and Daman and Diu          99.97
2                                    Mizoram          99.69
3                          Arunachal Pradesh          99.56
4                                Lakshadweep          99.54
5                                  Telengana          99.51
6                             Andhra Pradesh          99.37
7                                     Odisha          99.31
8                                  Rajasthan          99.27
9                                     Ladakh          99.22
10                                   Gujarat          99.14
11                                   Tripura          99.13
12                                 Karnataka          99.01
13                         Jammu and Kashmir          99.01
14                                   Haryana          99.00
15                               West Bengal          98.98
16                            Madhya Pradesh          98.98
17                                    Kerala          98.96
18                                Tamil Nadu          98.95
19                                     Assam          98.92
20                             Uttar Pradesh          98.89
21                                Puducherry          98.88
22                                    Sikkim          98.88
23                                Chandigarh          98.82
24                              Chhattisgarh          98.81
25                       Andaman and Nicobar          98.80
26                                 Jharkhand          98.80
27                          Himachal Pradesh          98.69
28                                     Delhi          98.69
29                                     Bihar          98.56
30                                       Goa          98.47
31                                   Manipur          98.47
32                                 Meghalaya          98.32
33                               Uttarakhand          98.28
34                               Maharashtra          98.18
35                                  Nagaland          97.83
36                                    Punjab          97.41

In [68]:
print("=== CASE FATALITY RATE PER STATE ===")
df['CFR'] = np.round((df['Deaths'].values / df['Total Cases'].values)*100, 2)
national_cfr = np.round(df['CFR'].mean(), 2)
print(f"National Average CFR: {national_cfr}%\n")
above_avg = df[df['CFR'] > national_cfr][['State/UTs','CFR']].sort_values('CFR', ascending=False)
print("States above national average CFR:")
print(above_avg.to_string(index=False))

=== CASE FATALITY RATE PER STATE ===
National Average CFR: 1.1%

States above national average CFR:
          State/UTs  CFR
             Punjab 2.44
           Nagaland 2.17
        Maharashtra 1.82
        Uttarakhand 1.72
          Meghalaya 1.68
            Manipur 1.53
                Goa 1.52
              Bihar 1.44
              Delhi 1.31
   Himachal Pradesh 1.31
Andaman and Nicobar 1.20
          Jharkhand 1.20
       Chhattisgarh 1.19
         Chandigarh 1.18
         Puducherry 1.12
             Sikkim 1.12
      Uttar Pradesh 1.11

In [ ]:
# y=df.sort_values(by='Total Cases',ascending=False,ignore_index=True)
# y['Rank']=range(1,37)
# y.insert(0,'Rank',range(1,37))
# y
top5 = df[['State/UTs','Total Cases','Deaths']].sort_values('Total Cases', ascending=False,ignore_index=True).head(5)
top5.index+=1
top5

        State/UTs  Total Cases  Deaths
1     Maharashtra      8171048  148558
2          Kerala      6907241   72042
3       Karnataka      4088769   40358
4      Tamil Nadu      3610655   38081
5  Andhra Pradesh      2340676   14733

In [ ]:
print("=== NATIONAL TOTALS USING NUMPY ===")
total_cases     = (df['Total Cases'].values).sum()
total_deaths    = np.sum(df['Deaths'].values)
total_recovered = np.sum(df['Discharged'].values)
total_active    = np.sum(df['Active'].values)
print(f"Total Cases     : {total_cases:,}")
print(f"Total Recovered : {total_recovered:,}")
print(f"Total Deaths    : {total_deaths:,}")
print(f"Total Active    : {total_active:,}")
recovery_rate = ((total_recovered/total_cases)*100).round(2)
death_rate    = np.round((total_deaths/total_cases)*100, 2)
print(f"\nRecovery Rate : {recovery_rate}%")
print(f"Death Rate    : {death_rate}%")

=== NATIONAL TOTALS USING NUMPY ===
Total Cases     : 44,999,085
Total Recovered : 44,465,246
Total Deaths    : 532,027
Total Active    : 1,812

Recovery Rate : 98.81%
Death Rate    : 1.18%

In [ ]:
print("=== DATASET OVERVIEW ===")
print("Total States & Union Territories:", len(df))
df[['Total Cases','Active','Discharged','Deaths']].describe()

=== DATASET OVERVIEW ===
Total States & Union Territories: 36

        Total Cases       Active    Discharged         Deaths
count  3.600000e+01    36.000000  3.600000e+01      36.000000
mean   1.249975e+06    50.333333  1.235146e+06   14778.527778
std    1.846038e+06   207.118048  1.820328e+06   27221.140636
min    1.076600e+04     0.000000  1.063700e+04       4.000000
25%    1.065430e+05     0.000000  1.055395e+05    1124.250000
50%    6.140910e+05     1.500000  6.076750e+05    6551.000000
75%    1.331951e+06     9.000000  1.322329e+06   14325.750000
max    8.171048e+06  1233.000000  8.022276e+06  148558.000000

In [ ]:
import pandas as pd
import numpy as np

# Read the file — replace 'your_file.csv' with the actual file name
df = pd.read_csv('Latest Covid-19 India Status.csv')

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
print(df.head())
print("\nNull values:")
print(df.isnull().sum())

Shape: (36, 9)

Columns: ['State/UTs', 'Total Cases', 'Active', 'Discharged', 'Deaths', 'Active Ratio', 'Discharge Ratio', 'Death Ratio', 'Population']

First 5 rows:
             State/UTs  Total Cases  Active  Discharged  Deaths  Active Ratio  \
0  Andaman and Nicobar        10766       0       10637     129           0.0
1       Andhra Pradesh      2340676       0     2325943   14733           0.0
2    Arunachal Pradesh        67049       0       66753     296           0.0
3                Assam       746159       5      738119    8035           0.0
4                Bihar       855267       1      842952   12314           0.0

   Discharge Ratio  Death Ratio  Population
0            98.80         1.20   100896618
1            99.37         0.63   128500364
2            99.56         0.44      658019
3            98.92         1.08      290492
4            98.56         1.44    40100376

Null values:
State/UTs          0
Total Cases        0
Active             0
Discharged         0
Deaths             0
Active Ratio       0
Discharge Ratio    0
Death Ratio        0
Population         0
dtype: int64

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Latest Covid-19 India Status.csv to Latest Covid-19 India Status.csv